<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ST.MS.FileUpload.Infra</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructures\ST.Infra.EntityFramework.Npgsql\ST.Infra.EntityFramework.Npgsql.csproj" />
    <ProjectReference Include="..\ST.MS.FileUpload.Domain\ST.MS.FileUpload.Domain.csproj" />
  </ItemGroup>

</Project>
