<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructures\ST.Infra.EventBus\ST.Infra.EventBus.csproj" />
    <ProjectReference Include="..\..\..\Infrastructures\ST.Infra.IntegrationEvents\ST.Infra.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\..\Infrastructures\ST.Infra.ReliableMessaging\ST.Infra.ReliableMessaging.csproj" />
    <ProjectReference Include="..\..\..\ServiceShared\ST.Shared.Application\ST.Shared.Application.csproj" />
    <ProjectReference Include="..\ST.MS.Order.Domain\ST.MS.Order.Domain.csproj" />
    <ProjectReference Include="..\ST.MS.Order.Infra\ST.MS.Order.Infra.csproj" />
  </ItemGroup>

</Project>
