# Grafana 数据源预置 — Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
