<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ServiceShared\ST.Shared.Application\ST.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\Infrastructures\ST.Infra.Redis\ST.Infra.Redis.csproj" />
    <ProjectReference Include="..\ST.MS.FileUpload.Domain\ST.MS.FileUpload.Domain.csproj" />
    <ProjectReference Include="..\ST.MS.FileUpload.Infra\ST.MS.FileUpload.Infra.csproj" />
  </ItemGroup>

</Project>
