<Project Sdk="Aspire.AppHost.Sdk/13.3.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.3.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.3.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Microservices\Gateway\ST.Gateway\ST.Gateway.csproj" />
    <ProjectReference Include="..\..\Microservices\Identity\ST.MS.Identity.Api\ST.MS.Identity.Api.csproj" />
    <ProjectReference Include="..\..\Microservices\OperationLog\ST.MS.OperationLog.Api\ST.MS.OperationLog.Api.csproj" />
    <ProjectReference Include="..\..\Microservices\OperationLog\ST.MS.OperationLog.Consumer\ST.MS.OperationLog.Consumer.csproj" />
    <ProjectReference Include="..\..\Microservices\Test\ST.MS.Test.Api\ST.MS.Test.Api.csproj" />
    <ProjectReference Include="..\..\Microservices\FileUpload\ST.MS.FileUpload.Api\ST.MS.FileUpload.Api.csproj" />
  </ItemGroup>

</Project>
